spring:
  application:
    name: SampleTaobao

mvf4ms:
  version: 3.1.0
  dependencies:
    - name: dependency1
      dependence:
        - id: pay
          serviceName: SampleAliPay
          patternUrl: /pay
          versions:
            - 3.3.1
        - id: delivery
          serviceName: SampleSF
          patternUrl: /delivery
          versions:
            - 4.1.1

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY}/eureka
